### ISSUE TITLE
Cannot parse region of repeat-masked genome

### ISSUE THREAD

**Issue by ksolmundson** [grenaud/ROHan#11]
Hi!
I am trying to run ROHan on BAM files that have been mapped to a repeat-masked reference genome. 
I am also using the repeat-masked reference when I run ROHan and it will start to run but then hit this error:
ERROR: Cannot parse region "Sc247Nf_89:1-1521"
I saw someone had a similar issue when their BAM and reference didn't match but I am fairly certain mine do...

However, I'm not sure if the error is occurring when parsing the BAM or the FASTA file...
I tried to remove that region of the BAM file to see if I could make it run but hit the same error message, so the issue must be with the repeat-masked FASTA?
I'm wondering if anyone has run ROHan with a repeat-masked genome before and if they had any issues? 
Is it not advisable to repeat-mask the genome when using ROHan?
I have successfully run ROHan on another BAM from the same individual where I did not repeat-mask the reference genome.

**Comment by grenaud** [comment]
Hello thank you for your interest in our software! I'm currently on
paternity leave and cannot do a lot of work so expect in replying. Are you
absolutely sure that you're using the exact fasta file that you used for
mapping? Also beware as the chromosome names are case-sensitive.

**Comment by ksolmundson** [comment]
Thanks for getting back to me despite your leave!
I went back through my code and I'm certain I am using the correct
reference genome.
I was able to get a section to run by extracting a single scaffold from the
BAM and the reference, but I do think the issue may be related to the fasta
headers.
I'm attempting to see if repeat-masking affects the results so I could
potentially just continue on this way by comparing results from single
scaffolds with and without repeat-masking.

---
Kirsten Solmundson
PhD Candidate, Trent University (2023)
BSc Hons, University of Manitoba (2017)
Email: ***@***.***
Website: *www.kirstensolmundson.wordpress.com
***@***.***>*
Twitter: @kirstensols
Phone: (204) 295-7665

**Comment by grenaud** [comment]
Could you provide the full command line as well as send me maybe some
relevant files (ex: the header of the bam file, the fasta index and
the bed file)?

**Comment by ksolmundson** [comment]
Full command line:./rohan/src/rohan --rohmu 5e-4 --tstv 1.97428 --size 50000 -o NAME_repeatmask ./genome_masked.fasta ./NAME_masked.bam
#ERROR: Cannot parse region "Sc247Nf_89:1-1521"

fasta index:
[genome_masked.fasta.fai.txt](https://github.com/grenaud/ROHan/files/6385735/genome_masked.fasta.fai.txt)
header of bam file:
[NAME_bam_masked_header.txt](https://github.com/grenaud/ROHan/files/6385736/NAME_masked_bam_header.txt)

By bed file do you mean the bed I used to extract a scaffold that successfully ran? Or the bed with the location that the error is (i.e. Sc247Nf_89: 1-1521) ?

**Comment by grenaud** [comment]
I just looked this. It seems you have scaffolds and not complete
chromosomes. ROHan will probably work unless the scaffolds are almost
chromosome level. ROHan uses the contiguous windows to assess the
heterozygous rate outside of ROH.

**Comment by ksolmundson** [comment]
Alright, I was able to run it before using the scaffold-level assembly (not repeat-masked) but I think repeat-masking reduced the scaffolds even further. I will have a chromosome-level assembly in the near future so I can try again soon. Thank you for your time!
