### ISSUE TITLE
minq filter for bam2prof for damaged rescaled BAMS?

### ISSUE THREAD

**Issue by saadarif** [grenaud/ROHan#19]
I am working with some musuem data where the individuals BAMs have been rescaled for deamination damage. When running Bam2prof should I set the minq to zero or is this not recommended?

On the ReadMe you mention this for the ancient BAM in the test data:
>Please be aware that the command for the profile uses no quality score filter: "-minq 0" because the quality scores were artificially >decreased to account for damage during calling. We generally do not recommend this as this will inflate substitution rate.

However it is not clear what the recommendation implies. Is it:
a) Don't use a  "-minq 0" for deamination profile if your BAMS are not damage rescaled, or,
b) Don't use damage rescaled BAMs for RoH inference with ROHan

Thanks in advance!

**Comment by grenaud** [comment]
If working with QC scores rescaled for damage, do not use minq 0
If working with unscaled bam (recommended), you can use minq and I even recommend it.

Hope this clarifies it!

**Comment by saadarif** [comment]
Many thanks for your prompt reponse. 

Could I just clarify that your recommendation for inferring RoH on damaged samples with ROHan would be to use damage **unscaled** BAMs and make a deamintation profile with **minq: 0**?

**Comment by grenaud** [comment]
yes sorry I thought I pressed "send" that is my recommendation.

Also, what is your coverage? ROHan will not work well on cov less than 5-7X for damaged samples.

**Comment by saadarif** [comment]
Thanks again for making it super clear.

The coverage of my samples varies between 3-10X. Roughly, a third are under 5X, and I will discount those, but a couple are just on the edge at 4.5 and 4.7x.

**Comment by grenaud** [comment]
you could run them and check.
Also, run with default parameters, check the het estimates pdf and hmm decoding, repeat maybe with a different mu value.
