### ISSUE TITLE
issue with using a bed file

### ISSUE THREAD

**Issue by angusdavison** [grenaud/ROHan#20]
Hi - I am wanting to analyse a subregion and also avoid repetitive regions, so am trying to use a bed file. The software is working when I use --size but I get an error when I substitute with --bed. The bed file is tab delimited and is fine as far as I know, it has the minimal 3 fields, exemplar below. Thanks!

Error:

Parsing arguments ......done
Computing average coverage..
Error in readBEDfile(): the following line does not have at least 3 fields

OZ073249.1      77201726        77202247
OZ073249.1      77202274        77202439
OZ073249.1      77203922        77204101
OZ073249.1      77205859        77206023
OZ073249.1      77207254        77207416
OZ073249.1      77207802        77208094
OZ073249.1      77208125        77208527
OZ073249.1      77209182        77209365
OZ073249.1      77212912        77213228

**Comment by grenaud** [comment]
hey! can you please send me the command line, a minimal BAM file, the bed file, the reference genome via email?

**Comment by angusdavison** [comment]
That's done - sent to gmail address :)

**Comment by grenaud** [comment]
there is an empty line at the bottom, is that the problem?

**Comment by angusdavison** [comment]
Of course! That fixed it - sorry to bother you with a bug that I should have spotted.
