### ISSUE TITLE
No range found using these chr/loci settings

### ISSUE THREAD

**Issue by Xnisongurumayum** [grenaud/ROHan#23]
Hello, 
I am encountering an error that returns "No range found using these chr/loci settings". I have used the same workflow which has worked for 4 other species. I have tried re-running it with the autosome list (and also redoing the whole workflow) - without success. 
Can you please let me know how to fix this?
I have run the following code:
$ /DATA/rohan/src/rohan -t 22 -o test wc_rerun_autosome.fa rerun_autosome_q30_sorted_rmdup.bam
|- Parsing arguments ......done
|- Computing average coverage..
|- No range found using these chr/loci settings

Thank you for your time and this amazing software.

**Comment by grenaud** [comment]
can you paste the output of "samtools view -H rerun_autosome_q30_sorted_rmdup.bam", run "samtools faidx wc_rerun_autosome.fa" followed by pasting the output of "cat wc_rerun_autosome.fa.fai"

**Comment by Xnisongurumayum** [comment]
$ samtools view -H rerun_autosome_q30_sorted.bam
@HD	VN:1.3	SO:coordinate
@SQ	SN:OX596294.1	LN:193917226
@SQ	SN:OX596295.1	LN:110124909
@SQ	SN:OX596296.1	LN:93282054
@SQ	SN:OX596298.1	LN:71401156
@SQ	SN:OX596299.1	LN:65169385
@SQ	SN:OX596300.1	LN:59508868
@SQ	SN:OX596301.1	LN:51870425
@SQ	SN:OX596302.1	LN:37003270
@SQ	SN:OX596303.1	LN:23436445
@SQ	SN:OX596304.1	LN:20483855
@SQ	SN:OX596305.1	LN:20202972
@SQ	SN:OX596306.1	LN:19443959
@SQ	SN:OX596307.1	LN:19163144
@SQ	SN:OX596308.1	LN:17784101
@SQ	SN:OX596309.1	LN:15031309
@SQ	SN:OX596310.1	LN:14534689
@SQ	SN:OX596311.1	LN:12783881
@SQ	SN:OX596312.1	LN:10722467
@SQ	SN:OX596313.1	LN:10601472
@SQ	SN:OX596314.1	LN:10183755
@SQ	SN:OX596315.1	LN:6885596
@SQ	SN:OX596316.1	LN:6652088
@SQ	SN:OX596317.1	LN:5890687
@SQ	SN:OX596318.1	LN:5462597
@SQ	SN:OX596319.1	LN:5332453
@SQ	SN:OX596320.1	LN:4897812
@SQ	SN:OX596321.1	LN:4546173
@SQ	SN:OX596322.1	LN:1377660
@SQ	SN:OX596323.1	LN:722708
@SQ	SN:OX596324.1	LN:1314461
@SQ	SN:OX596325.1	LN:1151599
@SQ	SN:OX596326.1	LN:1005284
@SQ	SN:OX596327.1	LN:836967
@SQ	SN:OX596328.1	LN:762006
@SQ	SN:OX596329.1	LN:623169
@SQ	SN:OX596330.1	LN:470437
@SQ	SN:OX596331.1	LN:229892
@SQ	SN:OX596332.1	LN:113925
@PG	ID:bwa	PN:bwa	VN:0.7.17-r1188	CL:bwa mem -t 22 wc_rerun_autosome.fa /DATA2/tennison/pheasants/western_capercaillie/ERR10501026/ERR10501026_1_PE.fastq.gz /DATA2/tennison/pheasants/western_capercaillie/ERR10501026/ERR10501026_2_PE.fastq.gz


$ cat wc_rerun_autosome.fa.fai 
OX596294.1	193917226	60	60	61
OX596295.1	110124909	197149300	60	61
OX596296.1	93282054	309109685	60	61
OX596298.1	71401156	403946500	60	61
OX596299.1	65169385	476537736	60	61
OX596300.1	59508868	542793338	60	61
OX596301.1	51870425	603294081	60	61
OX596302.1	37003270	656029074	60	61
OX596303.1	23436445	693649126	60	61
OX596304.1	20483855	717476240	60	61
OX596305.1	20202972	738301554	60	61
OX596306.1	19443959	758841304	60	61
OX596307.1	19163144	778609390	60	61
OX596308.1	17784101	798091981	60	61
OX596309.1	15031309	816172545	60	61
OX596310.1	14534689	831454437	60	61
OX596311.1	12783881	846231432	60	61
OX596312.1	10722467	859228439	60	61
OX596313.1	10601472	870129675	60	61
OX596314.1	10183755	880907900	60	61
OX596315.1	6885596	891261446	60	61
OX596316.1	6652088	898261863	60	61
OX596317.1	5890687	905024881	60	61
OX596318.1	5462597	911013808	60	61
OX596319.1	5332453	916567510	60	61
OX596320.1	4897812	921988899	60	61
OX596321.1	4546173	926968403	60	61
OX596322.1	1377660	931590407	60	61
OX596323.1	722708	932991089	60	61
OX596324.1	1314461	933725904	60	61
OX596325.1	1151599	935062334	60	61
OX596326.1	1005284	936233188	60	61
OX596327.1	836967	937255288	60	61
OX596328.1	762006	938106266	60	61
OX596329.1	623169	938881034	60	61
OX596330.1	470437	939514651	60	61
OX596331.1	229892	939992990	60	61
OX596332.1	113925	940226775	60	61

**Comment by grenaud** [comment]
ok this seems fine. However, I would recommend that you use a mappability track to get more accurate results, can you build one using either https://lh3lh3.users.sourceforge.net/snpable.shtml or genmap. Then feed the mappability bed file to ROHan and limit your analyses to those.

**Comment by grenaud** [comment]
--size is the window size if I remember correctly, I would leave it at 1Mb unless you have really high coverage.
