### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by jdmanthey** [grenaud/ROHan#3]
I have successfully installed the ROHan program on my desktop Mac, but am now trying to install on our HPCC. I have the prerequisite programs installed including cmake, git, zlib, etc. For some reason, the install cannot find deflate, and I don't know enough about zlib to understand why. 
I have attached the log here, and any suggestions would be much appreciated.
[log.txt](https://github.com/grenaud/ROHan/files/3740256/log.txt)

**Comment by grenaud** [comment]
Dear Joe, thank you for bringing this to my attention. Which linux distro do you run on your HPCC?

**Comment by jdmanthey** [comment]
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core)

**Comment by grenaud** [comment]
On this machine, could you give me the output of "rpm -qa | grep zlib"

**Comment by jdmanthey** [comment]
I get the following output:
zlib-1.2.7-17.el7.x86_64
zlib-devel-1.2.7-17.el7.x86_64

**Comment by grenaud** [comment]
Ok you got me there. I do not know why -lz is not detected with these libraries installed. However, I modified the Makefile and added "--without-zlib --without-png" when running configure. It removes the detection of -lz in libharu. Could you give it a spin?

**Comment by jdmanthey** [comment]
I reran the updated repository makefile, and it got much further in the install until another zlib error (see attached log file). Thanks for your help in this.
[log2.txt](https://github.com/grenaud/ROHan/files/3745253/log2.txt)

**Comment by jdmanthey** [comment]
I was playing around with different methods of trying to install. Originally, I was using GCC version: gcc (crosstool-NG fa8859cb) 7.2.0; I switched to a newer version (gcc (GCC) 7.3.0) and tried again, which seemed to get past the zlib error but gave a different error later on. I have attached the log file for this attempt that got the furthest. Now it got to a point where it cannot find: gsl/gsl_randist.h
[log3.txt](https://github.com/grenaud/ROHan/files/3745437/log3.txt)

**Comment by jdmanthey** [comment]
Sorry to spam this, but it appears that the gsl helper files needed are located here: /home/jmanthey/anaconda2/envs/rohan/include/gsl

May be helpful in a workaround solution?

**Comment by grenaud** [comment]
Sorry for the slow reply. What about installing: "gsl-devel" using yum install. I doubt C++ looks in "/home/jmanthey/anaconda2/envs/rohan/include/gsl"

**Comment by jdmanthey** [comment]
I think this is the main problem of why I am having issues is that I cannot have root access and all programs need to be installed into the user's directories or with package managers. For instance, the commands yum or sudo are unavailable to me.

**Comment by grenaud** [comment]
Is there a sysadmin around?

**Comment by jdmanthey** [comment]
If you think that is the only route to go I can try to work with the HPCC administrators. I usually try to avoid that because it generally takes weeks to get something installed this route. I will let you know any updates if I can get their help

**Comment by grenaud** [comment]
well there are 2 ways around this, 1) I send you an executable or 2) install locally. gsl is a pretty standard library. Let me know if you can get your admins to install gsl.

**Comment by jdmanthey** [comment]
Will do, and thank you again for your help while I am being difficult.

**Comment by grenaud** [comment]
no worries :-)

**Comment by jdmanthey** [comment]
I have worked on this issue for a few hours today and have figured out a solution. I found our HPCC already had gsl installed, but in a separate module that needed to be loaded. However, the compiler still could not find the gsl helper files. I ended up modifying the makefile in the src/ directory to include the location of the helper files on the CXXFLAGS line. This allowed the program to successfully install. After installation, the program required to know the location of the lib files as well, so I modified the LD_LIBRARY_PATH as to the location of the lib files in my user. 

Thanks for the help and glad I could find a workaround in the end. Interested to see how your program works on my data.

**Comment by grenaud** [comment]
Thank you for the feedback! Should I add something to the README that would make it easier for future users?

**Comment by jdmanthey** [comment]
I think that my case may be an outlier in general, where a computing cluster has a combination of modules and user environments interacting causing a problem. But I don't think it could hurt to point out the issue or at least leave a link to this issues page on github as a potential solution if anyone has the same problem.

**Comment by grenaud** [comment]
Sounds good, I will close this issue and leave it such that people who have similar issues can reference it. Let me know if you need help with the interpretation. Thank you for posting this!
