### ISSUE TITLE
ROH Length Distribution

### ISSUE THREAD

**Issue by AOHOSU** [grenaud/ROHan#4]
Dear ROHan developers,

Not so much an issue, but rather a recommendation.  I think it would be very useful to create a script to output raw, validated runs of homozygosity (ROH) lengths in order to i) create ROH size distribution frequency histograms, ii) locate the genomic coordinates of the ROHs, iii) perform non-parametric statistical tests between distributions from different samples, and, most importantly, iv) define size thresholds for long runs of homozygosity (LROH) from the ROH length distribution.

In this sense, an example output file could be:
ROH_ID	CHROM	BEGIN	END	ROH_LENGTH	VALIDATED_SITES?
1	A2	0	150000	150000	148564
2	B3	5000	15000	10000	9999
3	B3	25000	30000	5000	4756
...

Thanks!

AOH

**Comment by grenaud** [comment]
Hello! I have committed a new feature to produce the length to start with. It seems to work. it creates the 3 rohl.gz files that detail the length of the ROH. Keep the issue open, I need to hack a bit to produce the VALIDATED SITES as this information needs to be carried to the HMM subroutine. Thank you for your feedback!

**Comment by AOHOSU** [comment]
Thank you so much!  I will download and install the latest version of ROHan for this!
Thanks again!
AOH

**Comment by grenaud** [comment]
Please test it and see what happens. Please remember you do not need to
recompute the .hEst.gz file which takes a while. use the --hmm option.

**Comment by michaelbroe** [comment]
Hello, 

I installed the latest version of ROHan for a user who also wanted this functionality. The testData set worked perfectly. But both he and I are getting the same strange path behaviour when running rohan on our own data. The error message is this:

`Parsing arguments ......done
Computing average coverage..
Found read group file: sca1038.contig.15x.test1.rginfo.gz
lambda coverage=14.9944
RG:	1	PE	150
ERROR: Cannot find file /users/PAS0656/osu1112/local/src/ROHan/src//users/PAS0656/osu1112/local/src/ROHan/src/../preComputated/coverageprior/correctionCov_14.bin  containing pre-computed coverage weights`

This was produced using the following command:

`rohan --size 50000 --rohmu 5e-4 -o sca1038.contig.15x.test1 jcf7180000039762.fasta sca1038.contig.15x.bam`

If I first run the previous version of rohan however, which works correctly, and then run the same command with the `--hmm` option it seems to work perfectly.

Any suggestions?

**Comment by grenaud** [comment]
Hi Michael, a user had the same problem a week or so ago, I thought I fixed it. Could you give me the output of ".git/logs/HEAD" in your install directory?

**Comment by michaelbroe** [comment]
`0000000000000000000000000000000000000000 9b1dc5382933a398d3f6c2a4f3e8f50a6b0d0c2a Michael Broe <osu1112@pitzer-rw01.ten.osc.edu> 1573578120 -0500	clone: from https://github.com/grenaud/ROHan.git`

Thanks!

**Comment by grenaud** [comment]
thank you for confirming, this is indeed the lastest, let me have a look at the code.

**Comment by grenaud** [comment]
Ok found the problem! Another user was complaining that my method to get the path did not work when working with the path environment. By trying to fix that, it seems I broke the normal way. I tested it with path env., alias and full path. Please do a "git status" and "git pull origin master" and "make clean"  and "make". Let me if that works.

**Comment by michaelbroe** [comment]
Great, ran with no problems. Thanks for your prompt attention!

Turns out the user I was installing this for is... AOHOSU :)

If there are issues with the output he/we will follow up.

Thanks again.

**Comment by AOHOSU** [comment]
Dear Dr. Renaud,

I tested the newest version of ROHan on my end and it now works well!  It turns out I had asked user michaelbroe to run the previous "newest" version of ROHan for me so as to corroborate the bug prior to asking you about it haha -- michaelbroe had no idea it was me who initiated this issue string.  Anyhow, I would like to thank immensely (!!!) for your attention to this matter.  I shall now proceed with multiple ROHan runs and shall let you know if I have any issues in the future.

Thanks again!

AOH

**Comment by grenaud** [comment]
BTW, I am currently coding the genomic coordinates you requested.

**Comment by AOHOSU** [comment]
Wow!!!  Thank you so much!!!  That would be very helpful.

Cheers,

Alex

**Comment by grenaud** [comment]
Ok I think I am done, took longer than expected as I am on a train with a bad internet connection to my development server. Please do a "git status" and "git pull origin master" and "make clean" and "make" and try it to check if this what you requested.

**Comment by michaelbroe** [comment]
Thanks! Built and ran cleanly.

**Comment by grenaud** [comment]
and what the output as you requested? If so, I will close the issue.

**Comment by AOHOSU** [comment]
Yes.  I am confirming the output, specifically the rohl files, are what I requested.

Thanks again for everything!

AOH

**Comment by grenaud** [comment]
and thank you to both you and Michael for contributing to help this software!
