### ISSUE TITLE
ERROR: Cannot parse region

### ISSUE THREAD

**Issue by sagitaninta** [grenaud/ROHan#6]
Hi, I was trying to use ROHan on .bam files of a modern genome and got the following error message:

```
Parsing arguments ......done
Computing average coverage..
ERROR: Cannot parse region "JH374193.1:1-5700"                         ] 0 %
```

Could you please tell me what could possibly wrong?

**Comment by sagitaninta** [comment]
Oh sorry, it is just me using a different reference genome than the one I used to make the .bam files.

**Comment by grenaud** [comment]
that was the easiest and quickest issue I have ever had :-) thank you for your interest in glactools!
