### ISSUE TITLE
How to run ROHan on a separate chromosome

### ISSUE THREAD

**Issue by sagitaninta** [grenaud/ROHan#7]
Hi, I was trying to see if I can get my output faster by selecting only one chromosome for the input in ROHan. I was trying to get separate chromosome bam file through 
`samtools view -b in.bam chr2 > in.chr2.bam`
and then index it because ROHan cannot run without the index
`samtools index in.chr2.bam`
and run ROHan using the full reference genome file, 
`rohan --rohmu 2e-5 -o in.chr2.rohan ref.fa in.chr2.bam`

and this is what I got from the log:
```
Parsing arguments ......done
Computing average coverage..
[======================================================================] 100 %
..done
No data was found for the entire BAM file for the regions you defined, please verify the BAM file. 
The following regions had been selected. 
1	chr26:27000001-28000000
2	chr26:13000001-14000000
3	chr18:45000001-46000000
4	chr8:70000001-71000000
5	chr23:35000001-36000000
6	chr15:2000001-3000000
7	chr18:50000001-51000000
8	chr25:6000001-7000000
9	chr10:41000001-42000000
10	chr26:18000001-19000000
If you are running tests, you can use the hidden option --first it will select the first genomic windows. 
```

I got no other files with my output prefix. I do not quite understand what does it mean by no data was found for the entire BAM file for the region I defined as I did not specify any region. If what that means is the chr2, the in.chr2.bam was perfectly fine. Was it the reference? Should it be the chr2 only? But it reads the whole file without any problem...

I know I can specify the thread to make things faster but I was just curious. It works with the full bam file with the same reference genome (currently running).

**Comment by grenaud** [comment]
I see, normally ROHan uses 10 random windows to determine the average coverage. By default, they are selected at random. However, this can be overridden if you use --first. I see 2 options:
1) either use chr1 instead of chr2 and use --first.
2) I could modify the code so that a user could provide these regions via the command line. 

tell me which one works for you :-)

**Comment by sagitaninta** [comment]
Option 1 definitely works and this is fine, thanks! I was not using chr1 as it is the largest and I want to test it fast on smaller chromosomes... no idea if I will need option 2 in the future though.
